language: python
stages:
  - test
  - run
  - deploy

jobs:
  include:
#Linting test
    - stage: test
      install: pip install pycodestyle
      name: "Linting with pycodestyle (PEP-8)"
      python: "3.6"
      script: find . -name \*.py -exec pycodestyle {} +

# Test install the module
    - stage: test
      install: pip install -U pip setuptools wheel
      name: "Setup test"
      python: "3.6"
      script: python setup.py test

# Run functions
    - stage: run
      install: pip install -U pip setuptools wheel
      name: "Run the module funtions"
      python: "3.6"
      script:
        - python setup.py install
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('pip', 'stable'))"
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('pip', 'beta'))"
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('hassio', 'stable'))"
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('hassio', 'beta'))"
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('docker', 'stable'))"
        - python -c"from pyhaversion import HAVersion; print(HAVersion().get_version_number('docker', 'beta'))"


# Deploy to PyPi if all tests pass and change was done on master.
    - stage: deploy
      install: pip install -U pip setuptools wheel
      script: skip 
      provider: pypi
      user: "$PYPIUSER"
      password: "$PYPIKEY"
      on:
        branch: master