language: python
install: pip install pycodestyle

stages:
  - test
  - run
  - deploy

jobs:
  include:
#Linting test
    - stage: test
      name: "Linting with pycodestyle"
      python: "3.6"
      script: find . -name \*.py -exec pycodestyle {} +

# Test install the module
    - stage: test
      name: "Setup test"
      python: "3.6"
      script: python setup.py test

# Run functions
    - stage: run
      name: "Run the module funtions"
      python: "3.6"
      script:
        - python setup.py
        - python -m pyhaversion.get_version_number('pip', 'stable')
        - python -m pyhaversion.get_version_number('pip', 'beta')
        - python -m pyhaversion.get_version_number('hassio', 'stable')
        - python -m pyhaversion.get_version_number('hassio', 'beta')
        - python -m pyhaversion.get_version_number('docker', 'stable')
        - python -m pyhaversion.get_version_number('docker', 'beta')


# Deploy to PyPi if all tests pass and change was done on master.
    - stage: deploy
      provider: pypi
      user: "$PYPIUSER"
      password: "$PYPIKEY"
      on:
        branch: master